# Blog
keywords: Hexo,HTML,CSS,android,Linux
author: Author Name,name@example.com
description: Nothing lasts forever.
avatar: /images/avatar.jpg

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: x86core
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
